<MainScreen>:
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10
        Image: 
            id: img
            size_hint_y: 0.8
        TextInput:
            id: user_query
            size_hint_y: 0.08
        Button:
            text: 'Search Image'
            size_hint_y: 0.08 
            on_press: root.set_image()

<RootWidget>:
    MainScreen:
        id: main_screen
        name:  'main_screen'